### ISSUE TITLE
Endless compiling task encountered

### ISSUE THREAD

**Issue by cdluminate** [debomatic/debomatic-webui#17]
Hi,

http://debomatic-amd64.debian.net/distribution#experimental/meta-torch-core-free/1~exp2/buildlog

I uploaded this package yesterday and ridiculously it is not completed yet. It is merely a metapackage,
and should never cost more than a day to build. There must be trouble, please examine it.

**Comment by cdluminate** [comment]
During the autopkgtest procedure of that package, it emits a SIGILL. It that signal the trouble of source?

**Comment by LeoIannacone** [comment]
The webui just relies on the https://github.com/debomatic/debomatic-webui/blob/master/debomatic-modules/JSONLogger.py module.

That modules listens to signals, if something goes wrong in the main service (debomatic) some of those signals may not be dispatched.

I think this is the case, we should then fix this in debomatic. @dktrkranz

**Comment by dktrkranz** [comment]
Indeed it's related to debomatic itself. I'll try to put it in debug mode, as I see some builds in the same status as well.
