### ISSUE TITLE
Handle new sbuild buildlogs

### ISSUE THREAD

**Issue by dktrkranz** [debomatic/debomatic-webui#8]
New debomatic sbuild backend generates two buildlog files:
 * package_version_architecture-timestampdate-timestamphour.build
 * package_version_architecture.build (symlink to the first one)

Ideally, debomatic-webui should display just one of them, preventing the other one from being displayed under the Files section.

Moreover, the old .buildlog file, which generated the build preview panel, should be decommissioned and replaced by one of the logs above.

**Comment by LeoIannacone** [comment]
This commit refers to this issue https://github.com/debomatic/debomatic/commit/650789fcf5c530998f6878590a735211b4e119fe
